seed: 42

data_root: data/synapse_seg
output_dir: outputs_synapse

split:
  train: 0.8
  val: 0.1
  test: 0.1

img_size: 512
batch_size: 2
epochs: 50
lr: 5.0e-5
weight_decay: 1.0e-4
num_workers: 4

num_classes: 14
binarize_masks: false
include_background_in_metric: false
include_background_in_loss: false
use_class_weights: true
ce_weight_coef: 1.0
dice_weight_coef: 1.0
foreground_aware_sampling: true
fg_sampling_strength: 2.0
class_names:
  - background
  - spleen
  - right_kidney
  - left_kidney
  - gallbladder
  - esophagus
  - liver
  - stomach
  - aorta
  - inferior_vena_cava
  - portal_splenic_vein
  - pancreas
  - right_adrenal
  - left_adrenal
